name: Front-end Ninja
description: Become a Front-end Ninja using Om; Classes start March 27th
meta_description: "Front-end Development Class using Om."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
google_analytics: 'UA-51523630-2'
domain_name: 'http://om-ninja.github.io'


# Details for the RSS feed generator
url:            'om-ninja.github.io'
author:         'Prabhas Pokharel & Nirab Pudasaini'
